### ISSUE TITLE
I have a problem about multiple image

### ISSUE THREAD

**Issue by miraclezqc** [krshrimali/Panorama-OpenCV#1]
when i use your code to stitch four images (include newspaper), the result is so bad.
Hope you can help me how to solve it! Thanks!

**Comment by krshrimali** [comment]
Can you please show the output you are getting? Will help to debug. Also, the project is under development, alignment and rotation is yet to be done. But the image should not be too bad.

**Comment by krshrimali** [comment]
Please note that the issues have been resolved. Recheck and if there is still an issue, you can post here again.
Thanks!
